---
- name: install packages for personal use via yum
  yum:
    name: "python,python-pip,python-devel"
    state: present
  become: yes
  when: ansible_distribution == 'CentOS'

- name: install packages for personal use via apt
  apt:
    name: "python,python-pip,python-dev"
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: upgrade pip if available
  pip:
    name: pip
    state: latest
  become: yes

- name: install packages for peresonal use via pip
  pip:
    name: 'flake8,pep8,"ipython<5",pylint'
  become: yes

- name: install ipdb specific version
  pip:
    name: ipdb
    version: 0.10.2
  become: yes
...
