---
- name: install vim for personal use via yum
  yum:
    name: "vim-common,vim-minimal,vim-enhanced,vim-filesystem"
    state: present
  become: yes
  when: ansible_distribution == 'CentOS'

- name: install vim for personal use via apt
  apt:
    name: "vim"
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: install packages for peresonal use via pip
  pip:
    name: 'ropevim,flake8'
  become: yes

- name: check my_settings_dir exists
  delegate_to: localhost
  stat:
    path: "{{ my_settings_dir }}"
  register: myset
  when: my_settings_dir is defined

- name: copy vim files
  when:
    - my_settings_dir is defined
    - myset.stat.isdir is defined
    - myset.stat.isdir
  block:
    - name: copy .vimrc to home directory
      copy:
        src: "{{ my_settings_dir }}/.vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"

    - name: copy .vim directory to home directory
      copy:
        src: "{{ my_settings_dir }}/.vim"
        dest: "{{ ansible_env.HOME }}"
...
