---
- name: install kerberos workstation
  package:
    name: krb5-workstation
    state: present
  become: yes

- name: copy kerberos configuration
  copy:
    src: krb5.conf
    dest: /etc/krb5.conf
    mode: 0644
  become: yes

- name: "enable rcm repo (RHEL {{ ansible_distribution_major_version }})"
  get_url:
    url: "{{ rcm_repo_url[ansible_distribution_major_version] }}"
    dest: /etc/yum.repos.d/rhpkg.repo
  become: yes

- name: install other packages
  yum:
    name:
      - brewkoji
      - redhat-rpm-config
      - rhpkg
      - rpm-build
      - rpmdevtools
      - mock
      - libffi-devel
        #      - deltarpm
      - createrepo
    state: installed
  become: yes

- name: add current user to mock group
  user:
    name: "{{ ansible_env.USER }}"
    groups: mock
    append: yes
  become: yes

- name: add environment variable for brew SSL connection
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt'
