---
- name: install kerberos workstation
  package:
    name: krb5-workstation
    state: present
  become: yes

- name: copy kerberos configuration
  copy:
    src: krb5.conf
    dest: /etc/krb5.conf
    mode: 0644
  become: yes

- name: get Red Hat IT Root certificate authority
  get_url:
    url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
    dest: /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
    validate_certs: no
  become: yes

- name: get legacy certificate authority
  get_url:
    url: https://password.corp.redhat.com/legacy.crt
    dest: /etc/pki/ca-trust/source/anchors/legacy.crt
    validate_certs: no
  become: yes

- name: get Engineering certificate authority
  get_url:
    url: https://engineering.redhat.com/Eng-CA.crt
    dest: /etc/pki/ca-trust/source/anchors/Eng-CA.crt
    validate_certs: no
  become: yes

- name: update certificates
  shell: "update-ca-trust && update-ca-trust enable"
  become: yes

- name: WORKAROUND - remove urllib3 from pip
  pip:
    name: urllib3
    state: absent
  become: yes

- name: enable rcm repo
  get_url:
    url: "{{ rcm_repo_url }}"
    dest: /etc/yum.repos.d/rhpkg.repo
  become: yes

- name: install other packages
  yum:
    name:
      - brewkoji
      - redhat-rpm-config
      - rhpkg
      - rpm-build
      - rpmdevtools
      - mock
      - libffi-devel
        #      - deltarpm
      - createrepo
    state: installed
  become: yes

- name: add current user to mock group
  user:
    name: "{{ ansible_env.USER }}"
    groups: mock
    append: yes
  become: yes

- name: add environment variable for brew SSL connection
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt'
