---
- include_tasks: install_python3.yml

- name: clone devstack repo
  git:
    repo: "{{ devstack_repo }}"
    dest: "{{ devstack_dir }}"

- name: "WORKAROUND: Install virtualenv 16.2.0, the latest doesn't work"
  pip:
    name: virtualenv==16.2.0
    state: present
  become: yes

- name: "WORKAROUND: Install missing dependencies"
  yum:
    state: present
    name: "{{ item }}"
  become: yes
  with_items:
    - httpd
    - memcached
    - dstat

- name: flush iptables
  iptables: flush=true
  become: yes
  when: ansible_distribution != 'Fedora'

- set_fact:
    controller_host_ip: "{{ hostvars.controller.ansible_default_ipv4.address }}"

- name: create local.conf for controller
  template:
    src: local_{{ deployment_type }}.conf.j2
    dest: "{{ devstack_dir }}/local.conf"
    mode: 0644

- name: stack the stack
  command: ./stack.sh
  args:
    chdir: "{{ devstack_dir }}"
