---
- name: (CentOS 7) install pip for personal use via yum
  yum:
    name: "python,python-pip,python-devel"
    state: present
  become: yes
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "7"

- name: (CentOS 8 and 9) install pip for personal use via yum
  yum:
    name: "python3,python3-pip,python3-devel"
    state: present
  become: yes
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version in ["8", "9"]

- name: (Fedora) install pip for personal use via yum
  yum:
    name: "python3,python3-pip,python3-devel"
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'

- name: (Ubuntu) install packages for personal use via apt
  apt:
    name: "python3,python3-pip,python3-dev"
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: upgrade pip if available
  pip:
    name: pip
    state: latest
  become: yes
