---
- include_tasks: update.yml

- name: install development tools group (CentOS 7)
  package:
    name: "@development,epel-release"
    state: present
  become: yes
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "7"

- name: install development tools group (CentOS 8)
  package:
    name: "@development,epel-release"
    state: present
  become: yes
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "8"

- name: check my_settings_dir exists on local machine
  local_action: stat path={{ my_settings_dir }}
  register: myset
  when: my_settings_dir is defined

- block:
    - include_tasks: install_pip.yml
    - include_tasks: bash.yml
    - include_tasks: git.yml
    - include_tasks: python.yml
    - include_tasks: vim.yml
  ignore_errors: true
  when:
    - my_settings_dir is defined
    - myset.stat.isdir is defined
    - myset.stat.isdir
