---
- block:
  - name: install packages for peresonal use via pip (non Fedora)
    pip:
      name: 'flake8,pep8,ipython<5,pylint'
    become: yes

  - name: install ipdb specific version (non Fedora)
    pip:
      name: ipdb
      version: 0.10.2
    become: yes
  when: ansible_distribution != 'Fedora'

- name: install packages for peresonal use via pip (Fedora)
  pip:
    name: 'flake8,pep8,ipython,pylint,ipdb'
  become: yes
  when: ansible_distribution != 'Fedora'
...
