---
devstack_dir: ~/devstack
service_password: password
python3:
  package_requirements: sqlite-devel,zlib-devel,bzip2-devel,openssl-devel,ncurses-devel,sqlite-devel,readline-devel,tk-devel,gdbm-devel,db4-devel,libpcap-devel,xz-devel
  source_url: https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
  source_dir: /tmp/Python-3.5.1
  version: 3.5
deployment_type: ovn
devstack_repo: https://opendev.org/openstack-dev/devstack.git
