---
- name: clone ovn-heater repo
  ansible.builtin.git:
    repo: "{{ ovn_heater_repo }}"
    dest: "{{ ovn_heater_dir }}"

- name: install RPM dependencies
  ansible.builtin.dnf:
    name: "{{ rpm_install_list }}"
    state: present
  become: yes
